import { Partial, Number, Tuple } from 'runtypes';

export default Partial({
  weight: Number,
  health: Number,
  eneCap: Number,
  eneReg: Number,
  heaCap: Number,
  heaCol: Number,
  phyRes: Number,
  expRes: Number,
  eleRes: Number,
  phyDmg: Tuple(Number, Number),
  phyResDmg: Number,
  eleDmg: Tuple(Number, Number),
  eneDmg: Number,
  eneCapDmg: Number,
  eneRegDmg: Number,
  eleResDmg: Number,
  expDmg: Tuple(Number, Number),
  heaDmg: Number,
  heaCapDmg: Number,
  heaColDmg: Number,
  expResDmg: Number,
  walk: Number,
  jump: Number,
  range: Tuple(Number, Number),
  push: Number,
  pull: Number,
  recoil: Number,
  advance: Number,
  retreat: Number,
  uses: Number,
  backfire: Number,
  heaCost: Number,
  eneCost: Number
});
